---
title: "Distance and Counts"
author: "Luis A. Escobedo"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

library(sf)
library(tidyverse)
library(rgeos)
library(rgdal)

```

## R Markdown

```{r Loading Data, include = FALSE}

setwd("/Users/luchoescobedo/Documents/WORK/Projects/SpatialFunctions/")
locations <- read.csv("SubSample.csv")

head(locations)
str(locations)

```


```{r Transforming data, echo=FALSE, include = FALSE}

# Reading the data
locations_sf <- st_as_sf(locations, coords = c("lon", "lat"), crs = "+init=epsg:4326")
locations_sf_utm <- st_transform(locations_sf, 32718)

# Splitting the data
competitor <- locations_sf_utm %>% filter(class == "Competitor")
client <- locations_sf_utm %>% filter(class == "Client")

```

```{r Constructing the buffer}
buffers <- st_buffer(client, 50)

```

```{r Count function}

count_in_buffer <- function(entity, buffer) {
  temp = st_join(entity, buffer)
  temp2 = temp %>% 
          select(id.x, id.y) %>% 
          group_by(id.y) %>% 
          tally() %>% 
          mutate(n = n-1) %>% 
          rename(entity = id.y,
           count_buffer_50m = n,
           geometry = geometry)
  }


client_count <- count_in_buffer(client, buffers)
competitors_count <- count_in_buffer(competitor, buffers)


#test2 <- st_intersects(client, buffers, sparse = FALSE)

```





















