---
title: "Distance Matrix"
author: "Luis A. Escobedo"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

library(sp)
library(rgeos)
library(rgdal)
library(Imap)
library(dplyr)

```

## R Markdown

```{r Data}
setwd("/Users/luchoescobedo/Documents/WORK/Projects/SpatialFunctions/")
locations <- read.csv("LocationStores.csv")
locations_ss <- locations %>% select(id, lon, lat) %>% 
        rename(name = id, lon = lon, lat = lat)

head(locations_ss)
str(locations_ss)

```

## The Function

```{r Function, echo=FALSE}

# Distance matrix
ReplaceLowerOrUpperTriangle <- function(m, triangle.to.replace){
        # If triangle.to.replace="lower", replaces the lower triangle of a square matrix with its upper triangle.
        # If triangle.to.replace="upper", replaces the upper triangle of a square matrix with its lower triangle.
        if (nrow(m) != ncol(m)) stop("Supplied matrix must be square.")
        if (tolower(triangle.to.replace) == "lower") tri <- lower.tri(m)
        else if (tolower(triangle.to.replace) == "upper") tri <- upper.tri(m)
        else stop("triangle.to.replace must be set to 'lower' or 'upper'.")
        m[tri] <- t(m)[tri]
        return(m)
        }

DistanceMatrix <- function(df.geopoints){
        # Returns a matrix (M) of distances between geographic points.
        # M[i,j] = M[j,i] = Distance between (df.geopoints$lat[i], df.geopoints$lon[i]) and
        # (df.geopoints$lat[j], df.geopoints$lon[j]).
        # The row and column names are given by df.geopoints$name.
        DistanceInMetres <- function(g1, g2){
                # Returns a vector of distances. (But if g1$index > g2$index, returns zero.)
                # The 1st value in the returned vector is the distance between g1[[1]] and g2[[1]].
                # The 2nd value in the returned vector is the distance between g1[[2]] and g2[[2]]. Etc.
                # Each g1[[x]] or g2[[x]] must be a list with named elements "index", "lat" and "lon".
                # E.g. g1 <- list(list("index"=1, "lat"=12.1, "lon"=10.1), list("index"=3, "lat"=12.1, "lon"=13.2))
                DistM <- function(g1, g2){
                        require("Imap")
                        return(ifelse(g1$index > g2$index, 0, gdist(lat.1=g1$lat, lon.1=g1$lon, lat.2=g2$lat,
                                                                    lon.2=g2$lon, units="m")))
                        }
                return(mapply(DistM, g1, g2))
                }
        n.geopoints <- nrow(df.geopoints)
        # The index column is used to ensure we only do calculations for the upper triangle of points
        df.geopoints$index <- 1:n.geopoints
        
        # Create a list of lists
        list.geopoints <- by(df.geopoints[,c("index", "lat", "lon")],
                             1:n.geopoints, function(x){return(list(x))})
        
        # Get a matrix of distances (in metres)
        mat.distances <- ReplaceLowerOrUpperTriangle(outer(list.geopoints, list.geopoints,
                                                           DistanceInMetres), "lower")
        
        # Set the row and column names
        rownames(mat.distances) <- df.geopoints$name
        colnames(mat.distances) <- df.geopoints$name
        
        return(mat.distances)
        
        }

# Applying the Distance Matrix Function
dist_mat <- round(DistanceMatrix(locations_ss), 2)


```

